// @ts-nocheck
import {
  ChartMetadata,
  ChartPlugin,
  ChartProps,
  QueryFormData,
} from "@superset-ui/core";
import buildQuery from "./plugin/buildQuery";
import controlPanel from "./plugin/controlPanel";

export const metadata = new ChartMetadata({
  name: "{{PLUGIN_LABEL}}",
  description: "Generated by create-primebiplugin",
  thumbnail: "",
  useLegacyApi: false,
  tags: ["PrimeBI"],
});

// Class name will be replaced to {{PLUGIN_CLASS_NAME}} by the generator
export default class PrimeBIChartPlugin extends ChartPlugin {
  constructor() {
    super({
      metadata,
      buildQuery,
      controlPanel,
      loadChart: () => import("./plugin/ReactComponent"),
    });
  }
}

export type PrimeBIQueryFormData = QueryFormData;
export type PrimeBIChartProps = ChartProps;
